### ISSUE TITLE
PyPI package doesn't successfully pip install due to missing README.md

### ISSUE THREAD

**Issue by drakedevel** [guyzmo/Python-Octopart-API#2]
I was trying to install pyoctopart from PyPI and ran into an issue:

```
(ve) [adrake@duality octopart]$ pip install pyoctopart
Collecting pyoctopart
  Using cached pyoctopart-0.6.3.tar.gz
    Complete output from command python setup.py egg_info:

    Installed /tmp/pip-build-v898zrde/pyoctopart/.eggs/setuptools_markdown-0.2-py3.4.egg
    Searching for pypandoc
    Reading https://pypi.python.org/simple/pypandoc/
    Best match: pypandoc 1.1.3
    Downloading https://pypi.python.org/packages/source/p/pypandoc/pypandoc-1.1.3.zip#md5=771f376bf9c936a90159cd94235998c2
    Processing pypandoc-1.1.3.zip
    Writing /tmp/easy_install-rwxxk5jg/pypandoc-1.1.3/setup.cfg
    Running pypandoc-1.1.3/setup.py -q bdist_egg --dist-dir /tmp/easy_install-rwxxk5jg/pypandoc-1.1.3/egg-dist-tmp-oqygmjv_
    zip_safe flag not set; analyzing archive contents...
    pypandoc.__pycache__.__init__.cpython-34: module references __file__
    Patching wheel building...
    creating /tmp/pip-build-v898zrde/pyoctopart/.eggs/pypandoc-1.1.3-py3.4.egg
    Extracting pypandoc-1.1.3-py3.4.egg to /tmp/pip-build-v898zrde/pyoctopart/.eggs

    Installed /tmp/pip-build-v898zrde/pyoctopart/.eggs/pypandoc-1.1.3-py3.4.egg
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-v898zrde/pyoctopart/setup.py", line 28, in <module>
        'setuptools',
      File "/usr/lib64/python3.4/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/home/adrake/src/octopart/ve/lib64/python3.4/site-packages/setuptools/dist.py", line 272, in __init__
        _Distribution.__init__(self,attrs)
      File "/usr/lib64/python3.4/distutils/dist.py", line 280, in __init__
        self.finalize_options()
      File "/home/adrake/src/octopart/ve/lib64/python3.4/site-packages/setuptools/dist.py", line 327, in finalize_options
        ep.load()(self, ep.name, value)
      File "/tmp/pip-build-v898zrde/pyoctopart/.eggs/setuptools_markdown-0.2-py3.4.egg/setuptools_markdown.py", line 22, in long_description_markdown_filename
        output = pypandoc.convert(markdown_filename, 'rst')
      File "/tmp/pip-build-v898zrde/pyoctopart/.eggs/pypandoc-1.1.3-py3.4.egg/pypandoc/__init__.py", line 50, in convert
        outputfile=outputfile, filters=filters)
      File "/tmp/pip-build-v898zrde/pyoctopart/.eggs/pypandoc-1.1.3-py3.4.egg/pypandoc/__init__.py", line 68, in _convert
        raise RuntimeError('Missing format!')
    RuntimeError: Missing format!
```

What's going on here is that the pypandoc-0.6.3.tar.gz distribution is missing a `README.md` file, and `setuptools-markdown` is attempting to build it with `pypandoc` and failing. If you add an empty `README.md` to the tarball, setup.py never tries to pull in `pypandoc` and the installation succeeds without incident.

This issue only occurs in the PyPI package, since the git repo contains a `README.md`. The easiest fix would be to upload a new version to PyPI containing that file.

On a side note - the version in PyPI is 0.6.3 and the version in git is 0.6.2 -- is there another repo somewhere with the most up to date code?

**Comment by guyzmo** [comment]
> What's going on here is that the pypandoc-0.6.3.tar.gz distribution is missing a README.md file, and setuptools-markdown is attempting to build it with pypandoc and failing.

I have reuploaded the package to pypi, and it should be a 1:1 match with the git repository. And I'm sure there's a README.md in the package now ☺

> On a side note - the version in PyPI is 0.6.3 and the version in git is 0.6.2 -- is there another repo somewhere with the most up to date code?

thank you I forgot to push a commit O:-)

Please double check that everything's fine on your side, and don't hesitate to reopen if it's still broken. Also, please tell me if the package is still connecting to octopart's APIs, as it's been quite a while I haven't worked on that project ;-)

**Comment by erm3nda** [comment]
Seems this problem still occurs on the armhf package. I tried to install from github repo but still getting the same problem.
